[package]
name = "terraform-provider-corsschool"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
reqwest = "0.12.3"
terustform = { path = "../terustform" }

tokio = { version = "1.37.0", features = ["full"] }
